---
name: build
on: [push, pull_request]
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.10.9"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
      - name: Run black
        run: |
          black --check .
      - name: Run Tests
        run: |
          py.test --cov=napalm --cov-report term-missing -vs
  release:
    name: Build wheels and upload
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements-dev.txt
      - name: Build wheel
        run: |
          python setup.py bdist_wheel --build-number $GITHUB_RUN_NUMBER
      - name: Upload Pypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}